# Generated by Django 3.2.20 on 2025-04-12 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20250412_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('emergency_name', models.CharField(blank=True, max_length=255)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('immunization', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('active_prescriptions', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('medication_allergy_list', models.TextField(blank=True)),
                ('current_problems_list', models.TextField(blank=True)),
                ('lab_results', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='accounts.patientprofile')),
            ],
        ),
    ]
