# Generated by Django 3.2 on 2025-04-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_insuranceclaim_scheduleappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
