# Generated by Django 3.2 on 2025-05-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_scheduleappointment_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleappointment',
            old_name='doctor',
            new_name='doctor_name',
        ),
    ]
