# Generated by Django 3.2 on 2025-05-04 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20250504_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
